### ISSUE TITLE
Multidomain Support dokumentieren und ordentlich machen

### ISSUE THREAD

**Issue by perryflynn** [anysrc/mdblog#33]
Multidomain Support dokumentieren und ordentlich machen

**Comment by perryflynn** [comment]
```yml
hostconfig:
   hosts:
      anysrc.net:
         forcehttps: true
         chroot: blog
      relaychat.eu:
         forcehttps: false
         chroot: relaychat
         index: /::e72dd53
   checktrustedhost: true
```

- SSL wird pro Domain (nicht) erzwungen
- Pro Domain kann ein Baisverzeichnis angegeben werden
- Für eine Domain kann eine URL als Startseite definiert werden
